### PR TITLE
release: 0.13.0

### PR DESCRIPTION
**Pull request by drymarau**

### CODE REVIEW

**Review by tpettersen — COMMENTED** [review]
There is quite many deprecations that should go from warning to error and error to removal. And, it would be nice to use the new APIs in the sample app aswell, meaning in the `:conference` module.
Want to do this now or wait for another day?

**Comment by drymarau** [comment]
> There are quite many deprecations that should go from warning to error and error to removal.

This has already been done for this release.

> And, it would be nice to use the new APIs in the sample app aswell, meaning in the :conference module.

There's really only `DegradationPreference` API, which is somewhat niche. We can cover that later if there's a demand. `ReferConferenceEvent` is implemented.

**Comment by tpettersen** [comment]
It is mostly related to the Messenger API. 
```
w: file:///Users/tpett/dev/pexip-android-sdk/sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceAction.kt:224:58 'message(String): Unit' is deprecated. Use Conference.messenger.send() instead.
w: file:///Users/tpett/dev/pexip-android-sdk/sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceEventsScreen.kt:43:33 'MessageReceivedConferenceEvent' is deprecated. Use Messenger to receive messages instead.
w: file:///Users/tpett/dev/pexip-android-sdk/sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceEventsScreen.kt:103:12 'MessageReceivedConferenceEvent' is deprecated. Use Messenger to receive messages instead.
w: file:///Users/tpett/dev/pexip-android-sdk/sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceEventsScreen.kt:121:22 'MessageReceivedConferenceEvent' is deprecated. Use Messenger to receive messages instead.
w: file:///Users/tpett/dev/pexip-android-sdk/sample/src/main/kotlin/com/pexip/sdk/sample/conference/ConferenceService.kt:54:9 'stopForeground(Boolean): Unit' is deprecated. Deprecated in Java
```

In `Conference`, `InfinityConference` and `ConferenceEvents` the deprecations for messenger was last adjusted 28th of february.

**Comment by drymarau** [comment]
> In `Conference`, `InfinityConference` and `ConferenceEvents` the deprecations for messenger was last adjusted 28th of february.

Everything that was planned for this release was already changed.

**Pull request merged**
